---
apiVersion: v1
kind: Service
metadata:
  name: mongomery
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: mongomery
    port: 8080 
  selector:
    app: mongomery
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongomery
spec:
  replicas: 1
  serviceName: mongomery
  selector:
    matchLabels:
      app: mongomery
  template:
    metadata:
      labels:
        app: mongomery
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - mongomery
            topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
        - name: docker
      containers:
        - name: mongomery
          imagePullPolicy: Always
          image: docker.pkg.github.com/pedro-gutierrez/mongomery/mongomery:latest
          ports:
            - name: mongomery
              containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: secrets
          env:
            - name: DEPLOYMENT_VERSION 
              value: "{{VERSION}}"
